### ISSUE TITLE
re-using rights.org vocabulary

### ISSUE THREAD

**Issue by pennyl67** [ld4lt/metashare#22]
In the ontology v2 a class has been introduced for "Access rights statement" in which it would be nice to re-use values from relevant vocabularies (e.g. COAR, rightsstatements.org and OMTD-SHARE  as used in OpenMinTeD). 
For rightsstatements.org the relevant values are declared as URIs but I'm not sure whether we can use each of these URIs as an individual or create an individual in our namespace and map this to the corresponding URI.
See for instance: https://rightsstatements.org/page/InC/1.0/?language=en

**Comment by vroddon** [comment]
Well, I do believe rightsstatements is too narrow. What are the precise needs?
