### ISSUE TITLE
range with subclasses

### ISSUE THREAD

**Issue by pennyl67** [ld4lt/metashare#30]
compatibleLexiconType: should have as values all subclasses of LexicalConceptualResource; how can this be defined?

**Comment by jmccrae** [comment]
The current version in the XML is as follows

```xml
    <ObjectPropertyRange>
        <ObjectProperty IRI="#compatibleLexiconType"/>
        <Class IRI="#LexicalConceptualResource"/>
    </ObjectPropertyRange>
```

This states that every value of `compatibleLexiconType` is an instance of `LexicalConceptualResource`.

Do you want the actual values of this to correspond to the subclasses of `LexicalConceptualResource`? As this is not generally possible or a good idea. Instead I think you need to introduce a class of `LexicalConceptualResourceType` and add individuals with the corresponding names, e.g., `Lexicon`, `FrameNet`.

**Comment by pennyl67** [comment]
Thanks!

> 

Do you want the actual values of this to correspond to the subclasses of LexicalConceptualResource? As this is not generally possible or a good idea. Instead I think you need to introduce a class of LexicalConceptualResourceType and add individuals with the corresponding names, e.g., Lexicon, FrameNet.
--
This is the way we had it before; but then we said it's redundant to have both subclasses & individuals (cf. Issue #18), so it was better to keep only subclasses.
If there's no other way of handling this, we can just be redundant in this case.

**Comment by jmccrae** [comment]
Yes, I suggest that we have a punning here so that the same URI is used for both the subclass and the individual

**Comment by gkirtzou** [comment]
That could be a solution to our problem, but bare in mind that if we follow this action, then our ontology will be OWL Full, meaning that we lose the guarantees other subsets of OWL (OWL DL and OWL Lite) do provide for reasoning systems.

https://www.w3.org/TR/owl-ref/#Sublanguage-def 

Though I am not sure, if the same applies for OWL2 language.

**Comment by pennyl67** [comment]
Done with the same URI for subclasses and individuals.
The same approach will also be used for similar cases (e.g. instances for Operation)
